import { collect } from "./src/collector.ts";
import { writeReport } from "./src/llm.ts";
import { getSettings, getSecrets } from "./src/store.ts";
const settings = await getSettings(); const secrets = await getSecrets();
const { activities } = await collect("2026-07-21", settings, { startHour: 8, endHour: 18 });
console.error("采集条数:", activities.length, " 模型:", settings.llmModel);
const t0 = Date.now();
const report = await writeReport("2026-07-21", activities, settings, secrets, []);
console.error("生成耗时(s):", ((Date.now()-t0)/1000).toFixed(1), " 字符:", report.length);
console.log("\n========== 日报预览（不发布飞书）==========\n");
console.log(report);
